== Les containers


== Pré-requis

Avant toute chose, assurez-vous d'avoir installé quelques outils de développement :  
- **OpenJDK** : environnement Java de dévelopement  
- **Maven** : outil de construction des applications Java  
- **Docker ou Podman** : outil qui va nous permettre de construire et exécuter des conteneurs

----

Le premier challenge va consister à containeriser une application.  
L'application à containeriser se trouve ici : https://gitlab.com/redhat-scholars/antennas-front

Pensez bien à forker ce dépôt ! Vous allez travailler sur cette application pendant les 2 prochaines journées.  

N'oubliez pas de packager votre application avant de commencer à la containeriser.  
Vous pouvez utiliser la commande Maven `mvn clean package`.


[#exercice1]
== Containeriser votre app [*Challenge 1.1*] __Beginner__

Pour ce premier challenge, vous allez utiliser Docker et un Dockerfile pour créer votre image de container.
Vous pouvez créer votre Dockerfile mais regardez le repo forké, il y a peut-être un Dockerfile déjà présent ;)

Vous allez ensuite devoir démarrer ce container et faire en sorte que le port 8080 soit bien exposé.

Et finalement démarrer encore une fois le container mais positionner une variable d'environnement `PING` avec la valeur `DIOD`.


=== Preuves à fournir 

* [*Challenge 1.1.1*] Screenshot du résultat du `docker build`
* [*Challenge 1.1.2*] Screenshot du résultat du `docker run` et le résultat du `curl localhost:8080/rest/ping`
* [*Challenge 1.1.3*] Screenshot du résultat du `curl localhost:8080/rest/ping` affichant `DIOD`


[#exercice2]
== Pousser vers une registry [*Challenge 1.2*] __Advanced__

Pour ce challenge vous allez devoir pousser votre image de container dans une registry. Pour cela, vous pouvez vous créer un compte sur https://quay.io/
Par défaut, les images possées vers quay.io sont privées : pour la deuxième partie du challenge, l'image devra être rendue publique.

=== Preuves à fournir 

* [*Challenge 1.2.1*] Screenshot de votre repo quay.io où l'on voit l'image de container.
* [*Challenge 1.2.2*] Screenshot de votre repo quay.io où l'on voit la visibilité de l'image.




