== Déployer votre image de container sur Openshift avec Gitlab CI/CD

Ce matin vous avez créé votre image de container, il est maintenant temps de la déployer sur votre cluster! 

=== Accès au cluster 

=== Déployer directement l'image sur OpenShift [*Challenge 2.1*]  __Beginner__

Utilisez la perspective "Developer" de votre console OpenShift pour déployer votre image.
Vous pouvez utiliser le projet **"default"** pour cette étape.  
Profitez en pour vous familiariser avec les objets OpenShift (POD, Deploymement, Service, Route ...).

==== Preuves à fournir 

* [*Challenge 2.1.1*] L'URL de la route de votre application
* [*Challenge 2.1.2*] Screenshot montrant que vous avez réussi à scaler l'application à 2 Pods
* [*Challenge 2.1.3*] Ajouter la vairiable d'environnement `PING` avec la valeur DIOD et vérifier que vous avez le même comportement que localement.


=== Déployer l'application sur Openshift avec Gitlab CI/CD [*Challenge 2.2*]  __Advanced__


==== Installer Un Gitlab Runner sur OpenShift

Pour ce challenge, créer le projet **"diod"** sur votre cluster OpenShift.

Avant de pouvoir utiliser Gitlab avec Openshift il faut que vous installiez un "Gitlab runner" sur Openshift.  Le runner est fourni par l'intermédiaire d'un Operator. Il va falloir que vous exploriez votre cluster pour trouver comment l'installer.  
N'oublier pas de créer un secret pour le runner avant de le déployer.  Pour faire cela vous devrez récupérer le token dans la partie Settings > CI/CD > Runners de votre projet Gitlab.  
Pour créer le secret, utiliser le manifest suivant (celui de la documentation étant mal formaté) :
```
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-runner-secret
type: Opaque
stringData:
    runner-registration-token: LE_TOKEN_GITLAB
```


Une fois installé le Gitlab runner vous allez devoir créer un pipeline (gitlab-ci.yml) pour builder l'application et le pousser vers Openshift (qui va s'occuper de containeriser l'application et faire un déploiement 'rolling').  
Il y a un gitlab-ci.yml déjà present dans le repo pour vous mettre en route, mais n’hésitez pas de le modifier.  Le meilleur gitlab-ci.yml gagnera peut-être quelques points bonus :)  
Les jobs auront besoin des droits corrects pour pouvoir manipuler votre projet Openshift.  Voici un exemple de comment configurer le RBAC si votre runner tourne dans le même projet (diod) que l'application: 

`oc policy add-role-to-user edit system:serviceaccount:diod:default -n diod
clusterrole.rbac.authorization.k8s.io/edit added: "system:serviceaccount:diod:default"`

==== Preuves à fournir 

* [*Challenge 2.2.1*] Screenshot de l'Operator installé
* [*Challenge 2.2.2*] Screenshot de Gitlab CI/CD qui montre que Gitlab s'est connecté avec le Runner qui tourne sur Openshift
* [*Challenge 2.2.3*] L'URL de votre repo Gitlab qui contient le pipeline (qui a bien évidemment réussi)
* [*Challenge 2.2.5*] Screenshot des resources k8s générées 

