== Déployer votre image de container sur Openshift avec Gitlab CI/CD

Ce matin vous avez créé votre image de container, il est maintenant temps de la déployer sur votre cluster! 

=== Accès au cluster 

=== Déployer directement l'image sur OpenShift [*Challenge 2.1*]  __Beginner__

Utilisez la perspective "Developer" de votre console OpenShift pour déployer votre image.

==== Preuves à fournir 

* [*Challenge 2.1.1*] L'URL de la route de votre application
* [*Challenge 2.1.2*] Screenshot montrant que vous avez réussis à scaler l'application à 2 Pods


=== Creer un pipeline Gitlab qui deploie l'application sur Openshift [*Challenge 2.2*]  __Advanced__

==== Créer un projet Gitlab
Accédez à Gitlab et créez un account + projet.

==== Installer Un Gitlab Runner sur OpenShift

Avant de pouvoir utiliser Gitlab avec Openshift il faut que vous installiez un "Gitlab runner" sur Openshift.  Le runner est fourni par l'intermédiaire d'un Operator. Il va falloir que vous exploriez votre cluster pour trouver comment l'installer.
N'oublier pas de créer un secret pour le runner avant de le deployer.  Pour faire cela vous devrez récupérer le token dans la partie Settings > CI/CD > Runners de votre projet Gitlab.  

Une fois installé le Gitlab runner vous allez devoir créer un pipeline (gitlab-ci.yml) pour créer un image Docker de l'application, le pusher vers un Container Registry et déclencher le déploiement dans Openshift.  [TODO - example repo]

==== Preuves à fournir 

* [*Challenge 2.2.1*] Screenshot de l'Operator installé
* [*Challenge 2.2.2*] Screenshot de Gitlab CI/CD qui montre que Gitlab s'est connecté avec le Runner qui tourne sur Openshift
* [*Challenge 2.2.3*] L'URL de votre repo Gitlab qui contient le pipeline (qui a bien évidemment réussi)
* [*Challenge 2.2.5*] Screenshot des resources k8s générées 

=== BONUS: Installer Gitlab Pipeline Trigger [*Challenge 2.3*] __Advanced__

On veut déclencher notre pipeline à chaque commit, pour cela il va falloir installer un Trigger.

==== Preuves à fournir 

* [*Challenge 3.2.1*] Screenshot du trigger qui déclenche le pipeline (ou screenshot du log)

