== Résilience et scalabilité

[#exercice1]
=== [*Challenge 5.1*]  Résilience et scalabilité __Beginner__
L'application `antennas-incident` a 2 endpoints qui fournissent des health checks : 

* `q/health/live` pour le liveness probe
* `q/health/ready` pour le readyness probe 

Il va falloir mettre à jour les resources K8s afin d'utiliser ces probes.  


Ensuite, il faut mettre en place un HPA (Horizontal Pod Autoscaler). Pensez aussi à baisser les resources disponibles de votre `Deployment` (Limit and Request), mettez des valeurs assez basse pour faire réagir le HPA. 

Voici un example d'un HPA : 

[.console-output]
[source,text]
----

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: example
  namespace: myspace
spec:
  scaleTargetRef:
    kind: Deployment
    name: mydeployment
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 10Mi

----

==== Preuves à fournir 

* [*Challenge 5.1.1*] Screenshot ou manifest yaml du déploiment d'antennas-incident montrant les `readinessProbe` et `livenessProbe`
* [*Challenge 5.1.2*] Screenshot de la console faisant apparaître "Autoscaled to ..." ou manifest yaml du HPA


[#exercice2]
=== [*Challenge 5.2*] Chaos Kube__Advanced__



==== Preuves à fournir 

* 




